/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    team: Team;
    media: Media;
    hero: Hero;
    users: User;
    gallery: Gallery;
    menuMainDish: MenuMainDish;
    menuAppetizerDish: MenuAppetizerDish;
    menuSteaksDish: MenuSteaksDish;
    menuSteaksSharing: MenuSteaksSharing;
    menuSanjisChoice: MenuSanjisChoice;
    vouchers: Voucher;
    orders: Order;
    admin: Admin;
    Oeffnungzeiten: Oeffnungzeiten;
    'consent-logs': ConsentLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    team: TeamSelect<false> | TeamSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    menuMainDish: MenuMainDishSelect<false> | MenuMainDishSelect<true>;
    menuAppetizerDish: MenuAppetizerDishSelect<false> | MenuAppetizerDishSelect<true>;
    menuSteaksDish: MenuSteaksDishSelect<false> | MenuSteaksDishSelect<true>;
    menuSteaksSharing: MenuSteaksSharingSelect<false> | MenuSteaksSharingSelect<true>;
    menuSanjisChoice: MenuSanjisChoiceSelect<false> | MenuSanjisChoiceSelect<true>;
    vouchers: VouchersSelect<false> | VouchersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    admin: AdminSelect<false> | AdminSelect<true>;
    Oeffnungzeiten: OeffnungzeitenSelect<false> | OeffnungzeitenSelect<true>;
    'consent-logs': ConsentLogsSelect<false> | ConsentLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: string;
  Mitarbeiter: string;
  Bild: string | Media;
  beschreibung?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: string;
  title: string;
  image: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage all users: admins, editors, and regular users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * User's first name
   */
  firstName?: string | null;
  /**
   * User's last name
   */
  lastName?: string | null;
  /**
   * User roles - Admin: full access, Editor: content management, User: basic access
   */
  roles?: ('admin' | 'editor' | 'user')[] | null;
  /**
   * Whether this user account is active
   */
  isActive?: boolean | null;
  /**
   * Last login date
   */
  lastLogin?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  title: string;
  images: string | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage main dishes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuMainDish".
 */
export interface MenuMainDish {
  id: string;
  position?: number | null;
  titleDE: string;
  price: number;
  descriptionDE?: string | null;
  descriptionEN?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage appetizer dishes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuAppetizerDish".
 */
export interface MenuAppetizerDish {
  id: string;
  position?: number | null;
  title: string;
  price: number;
  descriptionDE?: string | null;
  descriptionEN?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage steaks dishes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuSteaksDish".
 */
export interface MenuSteaksDish {
  id: string;
  titleDE: string;
  descriptionDE?: string | null;
  descriptionEN?: string | null;
  regionDE?: string | null;
  regionEN?: string | null;
  weightSmall?: number | null;
  priceSmall?: number | null;
  weightLarge?: number | null;
  priceLarge?: number | null;
  position?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage steaks sharing
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuSteaksSharing".
 */
export interface MenuSteaksSharing {
  id: string;
  titleDE: string;
  descriptionDE?: string | null;
  descriptionEN?: string | null;
  regionDE?: string | null;
  regionEN?: string | null;
  weightSmall?: number | null;
  priceSmall?: number | null;
  weightLarge?: number | null;
  priceLarge?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage sanjis choice
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuSanjisChoice".
 */
export interface MenuSanjisChoice {
  id: string;
  titleDE: string;
  steaktitle?: string | null;
  descriptionDE?: string | null;
  descriptionEN?: string | null;
  stake1?: string | null;
  price1?: number | null;
  stakeWeight1?: number | null;
  stake2?: string | null;
  price2?: number | null;
  stakeWeight2?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vouchers".
 */
export interface Voucher {
  id: string;
  /**
   * Unique voucher code (e.g., SANJIS2024)
   */
  code: string;
  /**
   * Voucher value in the specified currency (e.g., 25 for 25€)
   */
  value: number;
  /**
   * Currency of the voucher value
   */
  currency: 'EUR' | 'USD' | 'CHF';
  /**
   * Expiration date of the voucher
   */
  expiresAt: string;
  /**
   * Whether the voucher has been redeemed
   */
  isRedeemed?: boolean | null;
  /**
   * Date when the voucher was redeemed
   */
  redeemedAt?: string | null;
  /**
   * Related order ID when voucher was used
   */
  orderId?: string | null;
  /**
   * Optional description for the voucher
   */
  description?: string | null;
  /**
   * Last user who edited this voucher
   */
  updatedBy?: (string | null) | User;
  /**
   * History of edits to this voucher
   */
  editHistory?:
    | {
        editedAt: string;
        editor?: (string | null) | User;
        editorEmail?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Order amount in the specified currency
   */
  amount: number;
  /**
   * Currency of the order amount
   */
  currency: 'EUR' | 'USD' | 'CHF';
  /**
   * Current status of the payment
   */
  paymentStatus: 'pending' | 'paid' | 'failed';
  /**
   * Email address of the customer
   */
  customerEmail: string;
  /**
   * Stripe Payment Intent ID for tracking the payment
   */
  stripePaymentIntentId?: string | null;
  /**
   * Vouchers used in this order
   */
  vouchers?: (string | Voucher)[] | null;
  /**
   * Items included in this order
   */
  orderItems?:
    | {
        /**
         * Name of the ordered item
         */
        itemName: string;
        /**
         * Quantity of the item
         */
        quantity: number;
        /**
         * Price per unit
         */
        unitPrice: number;
        /**
         * Total price for this item (quantity * unitPrice)
         */
        totalPrice: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Date when the order was placed
   */
  orderDate: string;
  /**
   * Date when the payment was completed
   */
  paymentDate?: string | null;
  /**
   * Name of the customer
   */
  customerName?: string | null;
  /**
   * Phone number of the customer
   */
  customerPhone?: string | null;
  /**
   * Additional notes for the order
   */
  notes?: string | null;
  /**
   * Whether the order confirmation email was sent
   */
  emailSent?: boolean | null;
  /**
   * Date when the order confirmation email was sent
   */
  emailSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage admin panel settings and configurations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin".
 */
export interface Admin {
  id: string;
  /**
   * A descriptive title for this admin panel setting
   */
  title: string;
  /**
   * Category of this admin setting
   */
  category: 'site-config' | 'admin-settings' | 'system-config' | 'feature-flags' | 'api-settings';
  /**
   * Unique identifier for this setting (e.g., "maintenance_mode", "max_upload_size")
   */
  key: string;
  /**
   * The configuration value (can be JSON, string, number, etc.)
   */
  value?: string | null;
  /**
   * The data type of the value
   */
  dataType: 'string' | 'number' | 'boolean' | 'json' | 'array';
  /**
   * Description of what this setting controls and how to use it
   */
  description?: string | null;
  /**
   * Whether this setting is currently active/enabled
   */
  isActive?: boolean | null;
  /**
   * Whether this setting can be accessed by frontend/public API
   */
  isPublic?: boolean | null;
  /**
   * Which environments this setting applies to
   */
  environment?: ('development' | 'staging' | 'production')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage opening times
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Oeffnungzeiten".
 */
export interface Oeffnungzeiten {
  id: string;
  Feld1: string;
  Uhrzeit1?: string | null;
  Feld2?: string | null;
  Uhrzeit2?: string | null;
  Feld3?: string | null;
  Uhrzeit3?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-logs".
 */
export interface ConsentLog {
  id: string;
  consentId: string;
  timestamp?: string | null;
  /**
   * Anonymized IP Address (SHA-256)
   */
  ipHash?: string | null;
  preferences:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  userAgent?: string | null;
  policyVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'team';
        value: string | Team;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'hero';
        value: string | Hero;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'gallery';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'menuMainDish';
        value: string | MenuMainDish;
      } | null)
    | ({
        relationTo: 'menuAppetizerDish';
        value: string | MenuAppetizerDish;
      } | null)
    | ({
        relationTo: 'menuSteaksDish';
        value: string | MenuSteaksDish;
      } | null)
    | ({
        relationTo: 'menuSteaksSharing';
        value: string | MenuSteaksSharing;
      } | null)
    | ({
        relationTo: 'menuSanjisChoice';
        value: string | MenuSanjisChoice;
      } | null)
    | ({
        relationTo: 'vouchers';
        value: string | Voucher;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'admin';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'Oeffnungzeiten';
        value: string | Oeffnungzeiten;
      } | null)
    | ({
        relationTo: 'consent-logs';
        value: string | ConsentLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  Mitarbeiter?: T;
  Bild?: T;
  beschreibung?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  isActive?: T;
  lastLogin?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  images?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuMainDish_select".
 */
export interface MenuMainDishSelect<T extends boolean = true> {
  position?: T;
  titleDE?: T;
  price?: T;
  descriptionDE?: T;
  descriptionEN?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuAppetizerDish_select".
 */
export interface MenuAppetizerDishSelect<T extends boolean = true> {
  position?: T;
  title?: T;
  price?: T;
  descriptionDE?: T;
  descriptionEN?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuSteaksDish_select".
 */
export interface MenuSteaksDishSelect<T extends boolean = true> {
  titleDE?: T;
  descriptionDE?: T;
  descriptionEN?: T;
  regionDE?: T;
  regionEN?: T;
  weightSmall?: T;
  priceSmall?: T;
  weightLarge?: T;
  priceLarge?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuSteaksSharing_select".
 */
export interface MenuSteaksSharingSelect<T extends boolean = true> {
  titleDE?: T;
  descriptionDE?: T;
  descriptionEN?: T;
  regionDE?: T;
  regionEN?: T;
  weightSmall?: T;
  priceSmall?: T;
  weightLarge?: T;
  priceLarge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuSanjisChoice_select".
 */
export interface MenuSanjisChoiceSelect<T extends boolean = true> {
  titleDE?: T;
  steaktitle?: T;
  descriptionDE?: T;
  descriptionEN?: T;
  stake1?: T;
  price1?: T;
  stakeWeight1?: T;
  stake2?: T;
  price2?: T;
  stakeWeight2?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vouchers_select".
 */
export interface VouchersSelect<T extends boolean = true> {
  code?: T;
  value?: T;
  currency?: T;
  expiresAt?: T;
  isRedeemed?: T;
  redeemedAt?: T;
  orderId?: T;
  description?: T;
  updatedBy?: T;
  editHistory?:
    | T
    | {
        editedAt?: T;
        editor?: T;
        editorEmail?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  amount?: T;
  currency?: T;
  paymentStatus?: T;
  customerEmail?: T;
  stripePaymentIntentId?: T;
  vouchers?: T;
  orderItems?:
    | T
    | {
        itemName?: T;
        quantity?: T;
        unitPrice?: T;
        totalPrice?: T;
        id?: T;
      };
  orderDate?: T;
  paymentDate?: T;
  customerName?: T;
  customerPhone?: T;
  notes?: T;
  emailSent?: T;
  emailSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin_select".
 */
export interface AdminSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  key?: T;
  value?: T;
  dataType?: T;
  description?: T;
  isActive?: T;
  isPublic?: T;
  environment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Oeffnungzeiten_select".
 */
export interface OeffnungzeitenSelect<T extends boolean = true> {
  Feld1?: T;
  Uhrzeit1?: T;
  Feld2?: T;
  Uhrzeit2?: T;
  Feld3?: T;
  Uhrzeit3?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-logs_select".
 */
export interface ConsentLogsSelect<T extends boolean = true> {
  consentId?: T;
  timestamp?: T;
  ipHash?: T;
  preferences?: T;
  userAgent?: T;
  policyVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}